apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: nvidia-worker
  name: 99-kernel-args-blacklist-irdma
spec:
  kernelArguments:
    - "module_blacklist=irdma"