### invariants inside the image
base_image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0ec6a32535eeed2d3bc3947c652d5c6705f3385e968b59bcf6c778cfe5a4e62e
doca_version=3.2.2
rhel_version=9
epel_version=9
openvswitch_version=3.5

### build process invariants
image_path=quay.io/rh-ee-mbramnik/ecosys-nvidia/custom-coreos-image-doca-3-2-2-os-4-21-15
os_version_tag=4.21.15