### invariants inside the image
base_image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c15698e0c9344bad0dfdd02e299dec4ac2f41fc37c4d57a95c2a3b457236f04d
doca_version=3.2.2
rhel_version=9
epel_version=9
openvswitch_version=3.5
arch=x86_64

### build process invariants
image_path=quay.io/rh-ee-mbramnik/ecosys-nvidia/custom-coreos-image-doca-3-2-2-os-4-21-24
os_version_tag=4.21.24