apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nncp-mtu-eth-rail0
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
    - name: eth_rail0
      description: mtu 9216 eth_rail0 
      type: ethernet 
      state: up 
      mtu: 9216